### ISSUE TITLE
Add windows support

### ISSUE THREAD

**Issue by Hacksore** [lextoumbourou/idle#1]
Hi @lextoumbourou 

Currently, the Windows platform has no implementation so hence I'm opening this issue.

I had started https://github.com/Hacksore/winidle and I could merge in the code I have for windows if that's something you're interested in.

**Comment by lextoumbourou** [comment]
Hey mate. I didn't even get close to starting this project. Created the readme then forgot about it. Currently it supports no operating systems and has no working functionality 🙂

Feel free to take whatever you want from my project, however sparse
